### ISSUE TITLE
A proposed solution to the problem of overwriting configurations

### ISSUE THREAD

**Issue by Merott** [ngbp/warlock#6]
As you [mentioned in the Wiki](https://github.com/ngbp/warlock/wiki/Configuration#warlockjson), currently there is no functionality to completely overwrite a configuration object or value. I'm proposing a solution, which if you accept, I'll happily submit a PR for.

I'm proposing the following syntax for completely overwriting/replacing a configuration:

``` js
"tasks": {
   "karma": {
      "single-run": {
         "(replace)browsers": [
            "Firefox"
         ]
      }
   }
}
```

A small change in `deepmerge.js` makes this possible: https://github.com/Merott/warlock/commit/9ff08185ec411a232fed497adde9d775eabc8d19

``` js
Object.keys(src).forEach(function (key) {
    if(key.indexOf('(replace)') === 0) {
        dst[key.substr(9)] = src[key];
    }
    else if (typeof src[key] !== 'object' || !src[key]) { ...
```

Do you see any problems with that approach?

**Comment by joshdmiller** [comment]
You're right - this is _much_ cleaner than my ideas. We would obviously have to create a fork of the deep merge library (it's in there temporarily because the author can't push a bug fix needed by Warlock until his npm permissions get reset).

The _only_ thing I might change is the syntax itself. Maybe something shorter like just "r" or "ow" (overwrite). We could also just pick a shorthand character sequence like `^`, which is unlikely to be used as a key:

``` json
{
"tasks": {
   "karma": {
      "single-run": {
         "^browsers": [ "..." ]
      }
   }
}
```

Anyway, great idea!!!

**Comment by Merott** [comment]
I prefer `^`

I also originally considered using `^`, and the only reason I didn't use it was that I thought being a little more explicit with `(replace)` would make the syntax easier to understand. I have no real objection to `^` though, so I'd be happy with either of them.

**Comment by joshdmiller** [comment]
I prefer `^` too. I normally opt for clarity too, but in this case the aesthetics on the shorthand win me over. It's just easier to read for me. If you'd like to submit a PR, that'd be awesome!

However, we probably don't want to just change `deepmerge.js` as it'll be harder to merge upstream changes. Perhaps we should fork it and create a [`warlock-deepmerge`](https://github.com/ngbp/deepmerge) library we can throw on npm. We can then add a test case for that change too since we don't have unit testing on Warlock proper - yet (see #4). Then we get the added bonus of removing `deepmerge.js` from the Warlock repo.

What do you think?

**Comment by Merott** [comment]
Good plan. I'll write a test case for it and submit a PR to [`warlock-deepmerge`](https://github.com/ngbp/deepmerge).

**Comment by joshdmiller** [comment]
`warlock-deepmerge` has the change and all is groovy.
